# Generated by Django 3.1.2 on 2020-10-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=20)),
                ('beschreibung', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rezept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zutat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ZutatRezept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.CharField(max_length=20)),
                ('rezept_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_access.rezept')),
                ('zutat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_access.zutat')),
            ],
        ),
        migrations.CreateModel(
            name='RezeptQuelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stelle', models.CharField(max_length=150)),
                ('quelle_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_access.quelle')),
                ('rezept_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_access.rezept')),
            ],
        ),
    ]
