# Generated by Django 3.1.2 on 2020-10-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_access', '0002_remove_quelle_beschreibung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zutatrezept',
            name='menge',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
