# Generated by Django 3.1.2 on 2020-10-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_access', '0003_auto_20201013_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quelle',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
